In [1]:
import requests
import pandas as pd
import zipfile
import io
import os

import xml.etree.ElementTree as ET
import html

import numpy as np
os.makedirs("results/inputs_xml", exist_ok=True)
# ALL YEARS
years = ['2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']
# ONE YEARS:
# years = ['2007']

In [2]:
for year in years:
    print("LOAD", year)
    ###### LOAD DATAS XML TO DF ##########
    
    # Source = "https://www.prix-carburants.gouv.fr/rubrique/opendata/" (site gouvernemental)
    url = f"https://donnees.roulez-eco.fr/opendata/annee/{year}"
    
    response = requests.get(url)
    print(response)
    
    zip_file = zipfile.ZipFile(io.BytesIO(response.content))
    file_name = zip_file.namelist()[0]
    print(file_name)
    
    with zipfile.ZipFile(io.BytesIO(response.content), 'r') as zip_ref:
        zip_ref.extractall("results/inputs_xml")
    print(file_name, "extracted")
    
    
    tree = ET.parse(f"results/inputs_xml/PrixCarburants_annuel_{year}.xml")
    root = tree.getroot()
    
    data = []
    for pdv in root.findall("pdv"):
        for p in pdv.findall("prix"):
            row = {
                "id": pdv.get("id"),
                "latitude": pdv.get("latitude"),
                "longitude": pdv.get("longitude"),
                "cp": pdv.get("cp"),
                "ville": pdv.find("ville").text if pdv.find("ville") is not None and pdv.find("ville").text else None,
                "adresse": pdv.find("adresse").text.replace(",", " ").replace(";", " ") if pdv.find("adresse") is not None and pdv.find("adresse").text else None,
                "nom": p.get("nom"),
                "maj": p.get("maj"),
                "valeur": p.get("valeur")
            }
            data.append(row)
    
    df = pd.DataFrame(data)
    
    ###### CLEAN DF AND ADD TYPES ##############
    
    print(df.dtypes)
    
    df["id"] = df["id"].astype(int)
    df["latitude"] = df["latitude"].replace(["", "0"], np.nan).astype(float)
    df["longitude"] = df["longitude"].replace(["", "0"], np.nan).astype(float)
    df['adresse'] = df['adresse'].str.replace("\n", " ", regex=True)
    df["valeur"] = df["valeur"].astype(float)
    
    # (le cp est de valeur '35***' sur une des valeurs de 2008 et son id "35200004" ne correspond a aucune station sur d'autres année, donc on supprime.)
    df = df[df["cp"] != "35***"]
    df["cp"] = df["cp"].replace("", np.nan).astype(int)
    
    
    # (format date used between 2014 and now)
    df['maj_without_microsec_with_T'] = pd.to_datetime(df['maj'], format='%Y-%m-%dT%H:%M:%S', errors='coerce').dt.strftime('%Y_%m_%d')
    # (format date used between 2007 and 2013)
    df['maj_without_microsec'] = pd.to_datetime(df['maj'], format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.strftime('%Y_%m_%d')
    df['maj_with_microsec'] = pd.to_datetime(df['maj'], format='%Y-%m-%d %H:%M:%S.%f', errors='coerce').dt.strftime('%Y_%m_%d')
    
    df['maj'] = df['maj_with_microsec'].fillna(df['maj_without_microsec']).fillna(df['maj_without_microsec_with_T'])
    df = df.drop(columns=["maj_without_microsec", "maj_with_microsec", "maj_without_microsec_with_T"])

    # values format used between 2007 and 2021 = 500 to 2000
    # values format used between 2022 ans now = 0.5 to 2.0 (need to be adapted to 500 to 2000)
    df['valeur'] = df['valeur'] * 1000 if int(year) > 2021 else df['valeur']
    
    print(df.dtypes)
    
    ########### SAVE DF TO CSV ###################
    
    os.makedirs("results/inputs_csv", exist_ok=True)
    df.to_csv(f"results/inputs_csv/PrixCarburants_annuel_{year}.csv", index=False)
    print(df.head(5))
    # check null values for all columns
    print("CHECK , PROBLEMES --------------------")
    print(df.isnull().sum())

LOAD 2007
<Response [200]>
PrixCarburants_annuel_2007.xml
PrixCarburants_annuel_2007.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

           adresse     nom         maj  valeur
0  ROUTE NATIONALE  Gazole  2007_01_04   999.0
1  ROUTE NATIONALE  Gazole  2007_01_09   999.0
2  ROUTE NATIONALE  Gazole  2007_01_12   989.0
3  ROUTE NATIONALE  Gazole  2007_01_16   988.0
4  ROUTE NATIONALE  Gazole  2007_01_17   988.0
CHECK , PROBLEMES --------------------
id             0
latitude     213
longitude    213
cp             0
ville          0
adresse        0
nom          548
maj          548
valeur       548
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2008
<Response [200]>
PrixCarburants_annuel_2008.xml
PrixCarburants_annuel_2008.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

           adresse     nom         maj  valeur
0  ROUTE NATIONALE  Gazole  2008_01_04  1189.0
1  ROUTE NATIONALE  Gazole  2008_01_07  1199.0
2  ROUTE NATIONALE  Gazole  2008_01_15  1179.0
3  ROUTE NATIONALE  Gazole  2008_01_18  1169.0
4  ROUTE NATIONALE  Gazole  2008_01_19  1164.0
CHECK , PROBLEMES --------------------
id             0
latitude      11
longitude     11
cp             0
ville          0
adresse        0
nom          604
maj          604
valeur       604
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2009
<Response [200]>
PrixCarburants_annuel_2009.xml
PrixCarburants_annuel_2009.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

           adresse     nom         maj  valeur
0  ROUTE NATIONALE  Gazole  2009_01_05   909.0
1  ROUTE NATIONALE  Gazole  2009_01_08   935.0
2  ROUTE NATIONALE  Gazole  2009_01_10   965.0
3  ROUTE NATIONALE  Gazole  2009_01_16   965.0
4  ROUTE NATIONALE  Gazole  2009_01_21   965.0
CHECK , PROBLEMES --------------------
id              0
latitude       24
longitude      24
cp              0
ville           0
adresse         0
nom          1229
maj          1229
valeur       1229
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2010
<Response [200]>
PrixCarburants_annuel_2010.xml
PrixCarburants_annuel_2010.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

           adresse     nom         maj  valeur
0  ROUTE NATIONALE  Gazole  2010_01_02  1018.0
1  ROUTE NATIONALE  Gazole  2010_01_05  1028.0
2  ROUTE NATIONALE  Gazole  2010_01_06  1028.0
3  ROUTE NATIONALE  Gazole  2010_01_06  1039.0
4  ROUTE NATIONALE  Gazole  2010_01_07  1039.0
CHECK , PROBLEMES --------------------
id              0
latitude       81
longitude      81
cp              0
ville           0
adresse         0
nom          1718
maj          1718
valeur       1718
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2011
<Response [200]>
PrixCarburants_annuel_2011.xml
PrixCarburants_annuel_2011.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

           adresse     nom         maj  valeur
0  ROUTE NATIONALE  Gazole  2011_01_04  1202.0
1  ROUTE NATIONALE  Gazole  2011_01_05  1202.0
2  ROUTE NATIONALE  Gazole  2011_01_06  1205.0
3  ROUTE NATIONALE  Gazole  2011_01_08  1208.0
4  ROUTE NATIONALE  Gazole  2011_01_08  1211.0
CHECK , PROBLEMES --------------------
id              0
latitude       96
longitude      96
cp              0
ville           0
adresse         0
nom          1338
maj          1338
valeur       1338
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2012
<Response [200]>
PrixCarburants_annuel_2012.xml
PrixCarburants_annuel_2012.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

           adresse     nom         maj  valeur
0  ROUTE NATIONALE  Gazole  2012_01_02  1332.0
1  ROUTE NATIONALE  Gazole  2012_01_03  1336.0
2  ROUTE NATIONALE  Gazole  2012_01_05  1346.0
3  ROUTE NATIONALE  Gazole  2012_01_06  1355.0
4  ROUTE NATIONALE  Gazole  2012_01_07  1364.0
CHECK , PROBLEMES --------------------
id              0
latitude       71
longitude      71
cp              0
ville           0
adresse         0
nom          1229
maj          1229
valeur       1229
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2013
<Response [200]>
PrixCarburants_annuel_2013.xml
PrixCarburants_annuel_2013.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

           adresse     nom         maj  valeur
0  ROUTE NATIONALE  Gazole  2013_01_03  1299.0
1  ROUTE NATIONALE  Gazole  2013_01_04  1309.0
2  ROUTE NATIONALE  Gazole  2013_01_05  1309.0
3  ROUTE NATIONALE  Gazole  2013_01_07  1315.0
4  ROUTE NATIONALE  Gazole  2013_01_09  1315.0
CHECK , PROBLEMES --------------------
id              0
latitude       87
longitude      87
cp              0
ville           0
adresse         0
nom          1415
maj          1415
valeur       1415
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2014
<Response [200]>
PrixCarburants_annuel_2014.xml
PrixCarburants_annuel_2014.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

           adresse     nom         maj  valeur
0  ROUTE NATIONALE  Gazole  2014_01_02  1304.0
1  ROUTE NATIONALE  Gazole  2014_01_04  1304.0
2  ROUTE NATIONALE  Gazole  2014_01_05  1304.0
3  ROUTE NATIONALE  Gazole  2014_01_06  1304.0
4  ROUTE NATIONALE  Gazole  2014_01_07  1304.0
CHECK , PROBLEMES --------------------
id              0
latitude     3167
longitude    3167
cp              0
ville           0
adresse         2
nom          1326
maj          1326
valeur       1326
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2015
<Response [200]>
PrixCarburants_annuel_2015.xml
PrixCarburants_annuel_2015.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

                 adresse     nom         maj  valeur
0  596 AVENUE DE TREVOUX  Gazole  2015_01_02  1141.0
1  596 AVENUE DE TREVOUX  Gazole  2015_01_03  1141.0
2  596 AVENUE DE TREVOUX  Gazole  2015_01_07  1141.0
3  596 AVENUE DE TREVOUX  Gazole  2015_01_08  1115.0
4  596 AVENUE DE TREVOUX  Gazole  2015_01_09  1115.0
CHECK , PROBLEMES --------------------
id              0
latitude     3618
longitude    3618
cp              0
ville           0
adresse         0
nom          2601
maj          2601
valeur       2601
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2016
<Response [200]>
PrixCarburants_annuel_2016.xml
PrixCarburants_annuel_2016.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

                 adresse     nom         maj  valeur
0  596 AVENUE DE TREVOUX  Gazole  2016_01_02  1026.0
1  596 AVENUE DE TREVOUX  Gazole  2016_01_04  1026.0
2  596 AVENUE DE TREVOUX  Gazole  2016_01_04  1026.0
3  596 AVENUE DE TREVOUX  Gazole  2016_01_05  1026.0
4  596 AVENUE DE TREVOUX  Gazole  2016_01_07  1026.0
CHECK , PROBLEMES --------------------
id              0
latitude     2913
longitude    2913
cp              0
ville           0
adresse         0
nom          2659
maj          2659
valeur       2659
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2017
<Response [200]>
PrixCarburants_annuel_2017.xml
PrixCarburants_annuel_2017.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

                 adresse     nom         maj  valeur
0  596 AVENUE DE TREVOUX  Gazole  2017_01_02  1258.0
1  596 AVENUE DE TREVOUX  Gazole  2017_01_03  1258.0
2  596 AVENUE DE TREVOUX  Gazole  2017_01_06  1258.0
3  596 AVENUE DE TREVOUX  Gazole  2017_01_09  1258.0
4  596 AVENUE DE TREVOUX  Gazole  2017_01_10  1258.0
CHECK , PROBLEMES --------------------
id              0
latitude     1189
longitude    1189
cp              0
ville          39
adresse         0
nom          2870
maj          2870
valeur       2870
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2018
<Response [200]>
PrixCarburants_annuel_2018.xml
PrixCarburants_annuel_2018.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

                 adresse     nom         maj  valeur
0  596 AVENUE DE TREVOUX  Gazole  2018_01_06  1376.0
1  596 AVENUE DE TREVOUX  Gazole  2018_01_11  1389.0
2  596 AVENUE DE TREVOUX  Gazole  2018_01_12  1376.0
3  596 AVENUE DE TREVOUX  Gazole  2018_01_18  1376.0
4  596 AVENUE DE TREVOUX  Gazole  2018_01_18  1376.0
CHECK , PROBLEMES --------------------
id              0
latitude       74
longitude      74
cp              0
ville          53
adresse         0
nom          3128
maj          3128
valeur       3128
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2019
<Response [200]>
PrixCarburants_annuel_2019.xml
PrixCarburants_annuel_2019.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
3  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
4  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

                 adresse     nom         maj  valeur
0  596 AVENUE DE TREVOUX  Gazole  2019_01_04  1328.0
1  596 AVENUE DE TREVOUX  Gazole  2019_01_07  1348.0
2  596 AVENUE DE TREVOUX  Gazole  2019_01_10  1374.0
3  596 AVENUE DE TREVOUX  Gazole  2019_01_11  1387.0
4  596 AVENUE DE TREVOUX  Gazole  2019_01_14  1394.0
CHECK , PROBLEMES --------------------
id              0
latitude       74
longitude      74
cp              0
ville          30
adresse         0
nom          3295
maj          3295
valeur       3295
dtype: int64
Empty DataFrame
Columns: [id, latitude, longitude, cp, ville, adresse, nom, maj, valeur]
Index: []
LOAD 2020
<Response [200]>
PrixCarburants_annuel_2020.xml
PrixCarburants_annuel_2020.xml extracted
id           object
latitude     object
longitude    object
cp           object
ville        object
adresse      object
nom          object
maj          object
valeur       object
dtype: object
id             int32
latitude     float64
longitude    float64
cp             int32
ville         object
adresse       object
nom           object
maj           object
valeur       float64
dtype: object
        id   latitude  longitude    cp                  ville  \
0  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
1  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG
2  1000001  4620114.0   519791.0  1000  SAINT-DENIS-LèS-BOURG

### Analyses

In [3]:
print(f"ANALYSE {year}")

ANALYSE 2025

In [4]:
# check number of staions (id unique) and numbers of records
print("id unique", len(df["id"].unique()))

print("all values", len(df))

id unique 14092
all values 906848

In [5]:
# check null values for all columns
# df.isnull().sum()

In [6]:
# #check bad string
# print(df[df['adresse'].str.startswith("ZI La Laure", na=False)])

In [7]:
# # check what ID have None data
# df2 = df.copy()
# df2 = df2[df2['adresse'].isna()]

# df2 = df2[["id", "adresse"]].drop_duplicates()
# df2.head(25)